apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stockle-ingress
  namespace: stockle
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /stockle(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: stockle-backend-service
            port:
              number: 8080
