apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stockle-ingress
  namespace: stockle
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
spec:
  ingressClassName: public
  rules:
    - host: api.stockle.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stockle-backend-service
                port:
                  number: 8080